MYSCALE_HOST = "msc-4a9e710a.us-east-1.aws.staging.myscale.cloud" # read-only database provided by MyScale
MYSCALE_PORT = 443
MYSCALE_USER = "chatdata"
MYSCALE_PASSWORD = "myscale_rocks"
OPENAI_API_BASE = "https://api.openai.com/v1"
OPENAI_API_KEY = "<your-openai-key>"
UNSTRUCTURED_API = "<your-unstructured-io-api>" # optional if you don't upload documents
AUTH0_DOMAIN = "<your-auth0-domain>"            # optional if you don't user management
AUTH0_CLIENT_ID = "<your-auth0-client-id>"      # optiona
